config/routes.rb
Rails.application.routes.draw do

  # get 'motos', to: 'motos#index'
  # get 'motos/:id', to: 'motos#show'
  # get 'motos/edit'
  # get 'motos/update'
  # get 'motos/new'
  # get 'motos/create'
  # get 'motos/dashboard'
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :motos, only: [ :index, :show ]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moto.rb
class Moto < ApplicationRecord
  belongs_to :user
  include PgSearch
  pg_search_scope :search_by_name_and_brand_and_moto_type,
    against: [ :name, :brand, :moto_type ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :motos

  #validates :user_name, :email, :dl_type, :experience, :birth_age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/motos_controller.rb
class MotosController < ApplicationController
  def index
    @motos = Moto.all
    if params[:query].present?
      sql_query = " \
      motos.brand LIKE :query \
      OR motos.name LIKE :query \
    "
    @motos = @motos.where(sql_query, query: "%#{params[:query]}%")
    else
      @motos = Moto.all
    end
  end

  def show
    @moto = Moto.find(params[:id])
  end

  def edit
  end

  def update
  end

  def new
  end

  def create
  end

  def dashboard
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/motos_helper.rb
module MotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HolaMoto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/motos/create.html.erb
<h1>Motos#create</h1>
<p>Find me in app/views/motos/create.html.erb</p>

app/views/motos/dashboard.html.erb
<h1>Motos#dashboard</h1>
<p>Find me in app/views/motos/dashboard.html.erb</p>

app/views/motos/edit.html.erb
<h1>Motos#edit</h1>
<p>Find me in app/views/motos/edit.html.erb</p>

app/views/motos/index.html.erb
<h1>Motos</h1>
<%= form_tag motos_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a moto"
  %>
<% end %>

<!-- the list of motos-->

<ul>
  <% @motos.each do |moto| %>
    <li><%= link_to moto.name, moto_path(moto) %></li>
  <% end %>
</ul>

app/views/motos/new.html.erb
<h1>Motos#new</h1>
<p>Find me in app/views/motos/new.html.erb</p>

app/views/motos/show.html.erb
<h1><%= @moto.name %> <%= @moto.brand %></small></h1>

<h2><%= @moto.year %></h2>
<h2> Type: <%= @moto.moto_type %> Mileage: <%= @moto.mileage %></h2>
<p>Parking type: <%= @moto.parking %></p>
<p>Link to view all</p>

app/views/motos/update.html.erb
<h1>Motos#update</h1>
<p>Find me in app/views/motos/update.html.erb</p>

app/views/users/interactions.html.erb
<h1>Users#interactions</h1>
<p>Find me in app/views/users/interactions.html.erb</p>

app/views/users/matches.html.erb
<h1>Users#matches</h1>
<p>Find me in app/views/users/matches.html.erb</p>

app/views/users/motos.html.erb
<h1>Users#motos</h1>
<p>Find me in app/views/users/motos.html.erb</p>